# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_to_worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19scheduler_to_worker.proto\x1a\x0c\x63ommon.proto\"\xc2\x01\n\rRunJobRequest\x12\x13\n\x0btrainer_ids\x18\x01 \x03(\x04\x12\x12\n\nworld_size\x18\x02 \x01(\r\x12\x13\n\x0bmaster_addr\x18\x03 \x01(\t\x12*\n\x06\x63onfig\x18\x04 \x03(\x0b\x32\x1a.RunJobRequest.ConfigEntry\x12\x18\n\x10local_batch_size\x18\x05 \x01(\r\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32p\n\x11SchedulerToWorker\x12\"\n\x06RunJob\x12\x0e.RunJobRequest\x1a\x06.Empty\"\x00\x12\x19\n\x05Reset\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1c\n\x08Shutdown\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_RUNJOBREQUEST = DESCRIPTOR.message_types_by_name['RunJobRequest']
_RUNJOBREQUEST_CONFIGENTRY = _RUNJOBREQUEST.nested_types_by_name['ConfigEntry']
RunJobRequest = _reflection.GeneratedProtocolMessageType('RunJobRequest', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _RUNJOBREQUEST_CONFIGENTRY,
    '__module__' : 'scheduler_to_worker_pb2'
    # @@protoc_insertion_point(class_scope:RunJobRequest.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _RUNJOBREQUEST,
  '__module__' : 'scheduler_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:RunJobRequest)
  })
_sym_db.RegisterMessage(RunJobRequest)
_sym_db.RegisterMessage(RunJobRequest.ConfigEntry)

_SCHEDULERTOWORKER = DESCRIPTOR.services_by_name['SchedulerToWorker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RUNJOBREQUEST_CONFIGENTRY._options = None
  _RUNJOBREQUEST_CONFIGENTRY._serialized_options = b'8\001'
  _RUNJOBREQUEST._serialized_start=44
  _RUNJOBREQUEST._serialized_end=238
  _RUNJOBREQUEST_CONFIGENTRY._serialized_start=193
  _RUNJOBREQUEST_CONFIGENTRY._serialized_end=238
  _SCHEDULERTOWORKER._serialized_start=240
  _SCHEDULERTOWORKER._serialized_end=352
# @@protoc_insertion_point(module_scope)
