# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import trainer_to_scheduler_pb2 as trainer__to__scheduler__pb2


class TrainerToSchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitJob = channel.unary_unary(
                '/TrainerToScheduler/InitJob',
                request_serializer=trainer__to__scheduler__pb2.InitJobRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.UpdateConfig = channel.unary_unary(
                '/TrainerToScheduler/UpdateConfig',
                request_serializer=trainer__to__scheduler__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )
        self.ShutDown = channel.unary_unary(
                '/TrainerToScheduler/ShutDown',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )


class TrainerToSchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitJob(self, request, context):
        """Initializes the job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Update Configuraton
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutDown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerToSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.InitJob,
                    request_deserializer=trainer__to__scheduler__pb2.InitJobRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=trainer__to__scheduler__pb2.UpdateConfigRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'ShutDown': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutDown,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrainerToScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainerToScheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainerToScheduler/InitJob',
            trainer__to__scheduler__pb2.InitJobRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainerToScheduler/UpdateConfig',
            trainer__to__scheduler__pb2.UpdateConfigRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShutDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainerToScheduler/ShutDown',
            common__pb2.Empty.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
