# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer_to_scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atrainer_to_scheduler.proto\x1a\x0c\x63ommon.proto\"$\n\x0eInitJobRequest\x12\x12\n\ntrainer_id\x18\x01 \x01(\x04\"\x90\x01\n\x13UpdateConfigRequest\x12\x30\n\x06\x63onfig\x18\x01 \x03(\x0b\x32 .UpdateConfigRequest.ConfigEntry\x12\x18\n\x10local_batch_size\x18\x02 \x01(\r\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x84\x01\n\x12TrainerToScheduler\x12\"\n\x07InitJob\x12\x0f.InitJobRequest\x1a\x06.Empty\x12,\n\x0cUpdateConfig\x12\x14.UpdateConfigRequest\x1a\x06.Empty\x12\x1c\n\x08ShutDown\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')



_INITJOBREQUEST = DESCRIPTOR.message_types_by_name['InitJobRequest']
_UPDATECONFIGREQUEST = DESCRIPTOR.message_types_by_name['UpdateConfigRequest']
_UPDATECONFIGREQUEST_CONFIGENTRY = _UPDATECONFIGREQUEST.nested_types_by_name['ConfigEntry']
InitJobRequest = _reflection.GeneratedProtocolMessageType('InitJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITJOBREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:InitJobRequest)
  })
_sym_db.RegisterMessage(InitJobRequest)

UpdateConfigRequest = _reflection.GeneratedProtocolMessageType('UpdateConfigRequest', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPDATECONFIGREQUEST_CONFIGENTRY,
    '__module__' : 'trainer_to_scheduler_pb2'
    # @@protoc_insertion_point(class_scope:UpdateConfigRequest.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _UPDATECONFIGREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:UpdateConfigRequest)
  })
_sym_db.RegisterMessage(UpdateConfigRequest)
_sym_db.RegisterMessage(UpdateConfigRequest.ConfigEntry)

_TRAINERTOSCHEDULER = DESCRIPTOR.services_by_name['TrainerToScheduler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATECONFIGREQUEST_CONFIGENTRY._options = None
  _UPDATECONFIGREQUEST_CONFIGENTRY._serialized_options = b'8\001'
  _INITJOBREQUEST._serialized_start=44
  _INITJOBREQUEST._serialized_end=80
  _UPDATECONFIGREQUEST._serialized_start=83
  _UPDATECONFIGREQUEST._serialized_end=227
  _UPDATECONFIGREQUEST_CONFIGENTRY._serialized_start=182
  _UPDATECONFIGREQUEST_CONFIGENTRY._serialized_end=227
  _TRAINERTOSCHEDULER._serialized_start=230
  _TRAINERTOSCHEDULER._serialized_end=362
# @@protoc_insertion_point(module_scope)
