# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_to_scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19worker_to_scheduler.proto\x1a\x0c\x63ommon.proto\"n\n\x15RegisterWorkerRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\x04\x12\x10\n\x08num_gpus\x18\x03 \x01(\r\x12\x0f\n\x07ip_addr\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\r\"S\n\x16RegisterWorkerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tworker_id\x18\x02 \x01(\x04\x12\x15\n\rerror_message\x18\x03 \x01(\t\" \n\x0b\x44oneRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x04\"\"\n\rKilledRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x04\x32\x96\x01\n\x11WorkerToScheduler\x12\x41\n\x0eRegisterWorker\x12\x16.RegisterWorkerRequest\x1a\x17.RegisterWorkerResponse\x12\x1c\n\x04\x44one\x12\x0c.DoneRequest\x1a\x06.Empty\x12 \n\x06Killed\x12\x0e.KilledRequest\x1a\x06.Emptyb\x06proto3')



_REGISTERWORKERREQUEST = DESCRIPTOR.message_types_by_name['RegisterWorkerRequest']
_REGISTERWORKERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterWorkerResponse']
_DONEREQUEST = DESCRIPTOR.message_types_by_name['DoneRequest']
_KILLEDREQUEST = DESCRIPTOR.message_types_by_name['KilledRequest']
RegisterWorkerRequest = _reflection.GeneratedProtocolMessageType('RegisterWorkerRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKERREQUEST,
  '__module__' : 'worker_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:RegisterWorkerRequest)
  })
_sym_db.RegisterMessage(RegisterWorkerRequest)

RegisterWorkerResponse = _reflection.GeneratedProtocolMessageType('RegisterWorkerResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERWORKERRESPONSE,
  '__module__' : 'worker_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:RegisterWorkerResponse)
  })
_sym_db.RegisterMessage(RegisterWorkerResponse)

DoneRequest = _reflection.GeneratedProtocolMessageType('DoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _DONEREQUEST,
  '__module__' : 'worker_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:DoneRequest)
  })
_sym_db.RegisterMessage(DoneRequest)

KilledRequest = _reflection.GeneratedProtocolMessageType('KilledRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLEDREQUEST,
  '__module__' : 'worker_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:KilledRequest)
  })
_sym_db.RegisterMessage(KilledRequest)

_WORKERTOSCHEDULER = DESCRIPTOR.services_by_name['WorkerToScheduler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERWORKERREQUEST._serialized_start=43
  _REGISTERWORKERREQUEST._serialized_end=153
  _REGISTERWORKERRESPONSE._serialized_start=155
  _REGISTERWORKERRESPONSE._serialized_end=238
  _DONEREQUEST._serialized_start=240
  _DONEREQUEST._serialized_end=272
  _KILLEDREQUEST._serialized_start=274
  _KILLEDREQUEST._serialized_end=308
  _WORKERTOSCHEDULER._serialized_start=311
  _WORKERTOSCHEDULER._serialized_end=461
# @@protoc_insertion_point(module_scope)
